# Media services for downloading and serving content (mostly) using images
# from [LinuxServer.io](https://docs.linuxserver.io/).

x-base-service: &base-service
  extends:
    file: ../common.yaml
    service: base

# All services need somewhere to store their configuration data
x-config-volume: &config-volume
  type: volume 
  source: config
  target: /config

x-media-volume: &media-volume
  type: volume
  source: media
  target: /data

services:

  # https://sabnzbd.org
  # https://docs.linuxserver.io/images/docker-sabnzbd/
  sabnzbd:
    <<: *base-service
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    ports:
      - 8888:8080
    volumes:
      - <<: *config-volume
        volume:
          subpath: sabnzbd
      - <<: *media-volume
        target: /data/downloads
        volume:
          subpath: downloads

  # https://radarr.video
  # https://docs.linuxserver.io/images/docker-readarr/
  radarr:
    <<: *base-service
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    ports:
      - 7878:7878
    volumes:
      - <<: *config-volume
        volume:
          subpath: radarr
      - <<: *media-volume

  # https://sonarr.tv
  # https://docs.linuxserver.io/images/docker-sonarr/
  sonarr:
    <<: *base-service
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    ports:
      - 8989:8989
    volumes:
      - <<: *config-volume
        volume:
          subpath: sonarr
      - <<: *media-volume

  # https://prowlarr.com
  # https://docs.linuxserver.io/images/docker-prowlarr/
  prowlarr:
    <<: *base-service
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    volumes:
      - <<: *config-volume
        volume:
          subpath: prowlarr

  # https://github.com/recyclarr/recyclarr
  recyclarr:
    <<: *base-service
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr:latest
    volumes:
      - <<: *config-volume
        volume:
          subpath: recyclarr
      - ./recyclarr.yml:/config/recyclarr.yml:ro

  # https://www.bazarr.media
  # https://docs.linuxserver.io/images/docker-bazarr/
  bazarr:
    <<: *base-service
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - 6767:6767
    volumes:
      - <<: *config-volume
        volume:
          subpath: bazarr
      - <<: *media-volume
        target: /data/content
        volume:
          subpath: content

  # https://jellyfin.org
  # https://docs.linuxserver.io/images/docker-jellyfin/
  jellyfin:
    <<: *base-service
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    ports:
      - 8096:8096
    volumes:
      - <<: *config-volume
        volume:
          subpath: jellyfin
      - <<: *media-volume
        target: /data/content
        volume:
          subpath: content

  # https://github.com/Fallenbagel/jellyseerr
  # https://hotio.dev/containers/jellyseerr/
  jellyseerr:
    <<: *base-service
    container_name: jellyseerr
    image: ghcr.io/hotio/jellyseerr
    ports:
      - 5055:5055
    volumes:
      - <<: *config-volume
        volume:
          subpath: jellyseerr